-*- mode: org; mode: visual-line; -*-
#+STARTUP: indent

* browser-2-arduino

Two-way communication between web browser and Arduino via websockets and Node.js serial proxy.

** Example 1: Single-Byte Communication

- Arduino LED 13 flashes regularly: this is being cued from code in the browser page, sending data (=X= or =Y=) via web socket to the Node server, which is forwarded over serial.
- Console log for the web page shows repeating cycle of letters from =A= to =J=: this is data being generated by the Arduino and coming in the opposite direction.
- Feedback is also given in the main HTML page using =jQuery= (which is loaded from a CDN, so the host machine must be online).

*** Setup

- Do an =npm install socket.io= in =proxy= directory.
- Also: =npm install express= for the proxy's web/socket server.
- Also: =npm install serialport= for serial communication. (TODO: check default baud rate.)
- Flash the example code =LED-demo.ino= into a nearby Arduino.
- Check =proxy.js= and correct the serial port name as necessary. (TODO: create a selection menu.)
- Launch server with: =node proxy.js=.
- Open browser page =localhost:3000=.

Issues: this all works fine for single-byte messages with no implicit state, but it not reliable for more complex data since there's no guarantee that Arduino and host will reliably synchronise at the message start points.

TODO: integrate [[https://github.com/cassiel/arduino-clj][arduino-clj]] and [[https://github.com/cassiel/arduino-polyglot][arduino-polyglot]] for more complex data.
